"""
PA 1: The USILang Grammar -- verification harness.

Run: python validate_bnf.py usilang.bnf
Prints the Success Token only if every check below passes.

You do not edit this file -- it reads whatever usilang.bnf you write
and builds a generic backtracking parser directly from your grammar's
rules to test it. See usilang.bnf.example for formatting reference if
you're unsure how your file should look (do not just copy it).
"""

import base64
import hashlib
import re
import sys
from typing import Dict, List, Optional, Tuple

ASSIGNMENT_ID = "PA01"
REQUIRED_NONTERMINALS = {"program", "statement", "declaration", "assignment", "expr", "term", "factor"}
REQUIRED_TERMINAL_CATEGORIES = {"NUMBER", "IDENT"}
REQUIRED_LITERALS = {"+", "-", "*", "/", "(", ")", "=", ";"}
MAX_RECURSION_DEPTH = 200


def get_student_id() -> str:
    """Prompt for the student's USI username; baked into the Success Token
    so a copied/shared token decodes to someone else's name, not yours."""
    student_id = input("Enter your USI username (e.g. cwill): ").strip()
    while not student_id:
        student_id = input("Username cannot be blank. Enter your USI username: ").strip()
    return student_id


def generate_token(assignment_id: str, student_id: str) -> str:
    digest = hashlib.sha256(f"CS379-{assignment_id}-{student_id}-VERIFIED".encode()).hexdigest()[:16]
    raw = f"CS379|{assignment_id}|{student_id}|PASS|{digest}"
    return base64.b64encode(raw.encode()).decode()


def print_success_banner(assignment_id: str) -> None:
    student_id = get_student_id()
    token = generate_token(assignment_id, student_id)
    print("\n" + "=" * 60)
    print(f"  ALL CHECKS PASSED -- {assignment_id}")
    print(f"  STUDENT: {student_id}")
    print("  SUCCESS TOKEN (paste this into Blackboard):")
    print(f"  {token}")
    print("=" * 60 + "\n")


def check(label: str, condition: bool, failures: list) -> None:
    status = "PASS" if condition else "FAIL"
    print(f"  [{status}] {label}")
    if not condition:
        failures.append(label)


# ---------------------------------------------------------------- BNF parsing

class GrammarError(Exception):
    pass


def parse_bnf(text: str) -> Dict[str, List[List[str]]]:
    """
    Parse .bnf text into {nonterminal: [ [symbol, symbol, ...], ... ]}.
    A symbol is either "<name>" (nonterminal, stored WITHOUT brackets),
    a quoted literal like "+" or '+' (stored as the literal), or a bare
    uppercase word like NUMBER (stored as-is, a terminal category).
    Epsilon (empty) productions may be written as an empty alternative.
    """
    # Strip comments and blank lines, but keep line structure for continuations.
    lines = []
    for raw_line in text.splitlines():
        line = re.sub(r"#.*$", "", raw_line).rstrip()
        if line.strip():
            lines.append(line)

    rule_starts = []
    for i, line in enumerate(lines):
        if re.match(r"^\s*<\w+>\s*::=", line):
            rule_starts.append(i)
    if not rule_starts:
        raise GrammarError("no rules found (expected lines like '<program> ::= ...')")

    blocks = []
    for idx, start in enumerate(rule_starts):
        end = rule_starts[idx + 1] if idx + 1 < len(rule_starts) else len(lines)
        blocks.append("\n".join(lines[start:end]))

    grammar: Dict[str, List[List[str]]] = {}
    for block in blocks:
        m = re.match(r"^\s*<(\w+)>\s*::=\s*(.*)$", block, re.DOTALL)
        if not m:
            raise GrammarError(f"malformed rule block: {block[:60]!r}")
        name, rest = m.group(1), m.group(2)
        if name in grammar:
            raise GrammarError(f"nonterminal <{name}> is defined more than once")
        alternatives = split_top_level_alternation(rest)
        grammar[name] = [tokenize_production(alt) for alt in alternatives]
    return grammar


def split_top_level_alternation(text: str) -> List[str]:
    """Split on '|' that isn't inside quotes."""
    parts, current, in_quote = [], [], None
    for ch in text:
        if in_quote:
            current.append(ch)
            if ch == in_quote:
                in_quote = None
        elif ch in ('"', "'"):
            in_quote = ch
            current.append(ch)
        elif ch == "|":
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    parts.append("".join(current))
    return parts


def tokenize_production(alt_text: str) -> List[str]:
    """Split one alternative's text into a list of grammar symbols."""
    symbols = []
    pattern = re.compile(r"""<\w+>|"[^"]*"|'[^']*'|\S+""")
    for match in pattern.finditer(alt_text):
        tok = match.group(0)
        if tok.startswith("<") and tok.endswith(">"):
            symbols.append(tok[1:-1])  # nonterminal, unbracketed
        elif (tok.startswith('"') and tok.endswith('"')) or (tok.startswith("'") and tok.endswith("'")):
            symbols.append(tok[1:-1])  # literal terminal
        elif tok.lower() in ("epsilon", "ε"):
            continue  # explicit epsilon marker -> empty production
        else:
            symbols.append(tok)  # bare terminal category, e.g. NUMBER
    return symbols


# ------------------------------------------------------------ fixed tokenizer
# Independent of student code -- PA1 has no lexer yet (that's PA2).

_TOKEN_SPEC = [
    ("NUMBER", r"\d+"),
    ("IDENT_OR_LET", r"[A-Za-z_][A-Za-z0-9_]*"),
    ("PLUS", r"\+"),
    ("MINUS", r"-"),
    ("STAR", r"\*"),
    ("SLASH", r"/"),
    ("LPAREN", r"\("),
    ("RPAREN", r"\)"),
    ("ASSIGN", r"="),
    ("SEMI", r";"),
    ("SKIP", r"[ \t\n]+"),
]
_MASTER_RE = re.compile("|".join(f"(?P<{name}>{pattern})" for name, pattern in _TOKEN_SPEC))


def fixed_tokenize(source: str) -> List[Tuple[str, str]]:
    """Returns a list of (category_or_literal, lexeme) pairs, ending in EOF."""
    tokens = []
    pos = 0
    while pos < len(source):
        m = _MASTER_RE.match(source, pos)
        if not m:
            raise GrammarError(f"test-suite tokenizer choked on {source[pos]!r} -- this is a harness bug, not your fault")
        kind = m.lastgroup
        lexeme = m.group()
        pos = m.end()
        if kind == "SKIP":
            continue
        if kind == "IDENT_OR_LET":
            tokens.append(("LET" if lexeme == "let" else "IDENT", lexeme))
        elif kind in ("PLUS", "MINUS", "STAR", "SLASH", "LPAREN", "RPAREN", "ASSIGN", "SEMI"):
            tokens.append((lexeme, lexeme))  # literal token: type == its own lexeme
        else:
            tokens.append((kind, lexeme))
    tokens.append(("EOF", ""))
    return tokens


# --------------------------------------------------------- generic BNF parser

def token_matches_symbol(symbol: str, token: Tuple[str, str]) -> bool:
    kind, lexeme = token
    if symbol in ("NUMBER", "IDENT"):
        return kind == symbol
    return kind == symbol or lexeme == symbol  # literal terminal


def try_parse(nonterminal: str, tokens: List[Tuple[str, str]], pos: int, grammar: dict, depth: int = 0) -> Optional[int]:
    if depth > MAX_RECURSION_DEPTH:
        raise GrammarError(f"recursion exceeded {MAX_RECURSION_DEPTH} while parsing <{nonterminal}> -- your grammar may be left-recursive")
    if nonterminal not in grammar:
        raise GrammarError(f"<{nonterminal}> is referenced but never defined")

    for alternative in grammar[nonterminal]:
        new_pos = pos
        ok = True
        for symbol in alternative:
            is_nt = symbol in grammar or (symbol.islower() and symbol not in REQUIRED_TERMINAL_CATEGORIES and not symbol.isupper())
            if symbol in grammar:
                result = try_parse(symbol, tokens, new_pos, grammar, depth + 1)
                if result is None:
                    ok = False
                    break
                new_pos = result
            else:
                if new_pos < len(tokens) and token_matches_symbol(symbol, tokens[new_pos]):
                    new_pos += 1
                else:
                    ok = False
                    break
        if ok:
            return new_pos
    return None


def accepts(grammar: dict, source: str) -> bool:
    tokens = fixed_tokenize(source)
    end = try_parse("program", tokens, 0, grammar)
    return end is not None and tokens[end][0] == "EOF"


# -------------------------------------------------------------- test suites

VALID_SNIPPETS = [
    "let x = 5;",
    "let y = x + 1;\nx = y * 2;",
    "let x = ((((1))));",
    "let a = 1;\nlet b = 2;\na = a + b * 3;",
    "let z = (1 + 2) * (3 - 4) / 5;",
    "let letter = 3;",  # 'letter' must be IDENT, not LET + 'ter'
]

INVALID_SNIPPETS = [
    "let = 5;",           # missing identifier
    "x 5;",                # missing '='
    "let x = 5",            # missing ';'
    "let x = ;",            # empty expression
    "x = (1 + 2;",          # unbalanced parens
    "let 5 = x;",            # NUMBER where IDENT expected
]


def structural_checks(grammar: dict, failures: list) -> None:
    for nt in REQUIRED_NONTERMINALS:
        check(f"<{nt}> is defined", nt in grammar, failures)

    referenced = set()
    for alts in grammar.values():
        for alt in alts:
            for symbol in alt:
                if symbol in grammar or symbol[:1].islower():
                    referenced.add(symbol)

    reachable = set()
    frontier = ["program"] if "program" in grammar else []
    while frontier:
        nt = frontier.pop()
        if nt in reachable or nt not in grammar:
            continue
        reachable.add(nt)
        for alt in grammar[nt]:
            for symbol in alt:
                if symbol in grammar:
                    frontier.append(symbol)
    for nt in grammar:
        check(f"<{nt}> is reachable from <program>", nt in reachable, failures)


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: python validate_bnf.py usilang.bnf")
        return 1

    failures: list = []
    try:
        with open(sys.argv[1], encoding="utf-8") as f:
            text = f.read()
        grammar = parse_bnf(text)
    except (OSError, GrammarError) as e:
        print(f"Could not parse grammar file: {e}")
        return 1

    print("Checking required structure...\n")
    structural_checks(grammar, failures)
    if failures:
        print(f"\n{len(failures)} structural check(s) failed. No token issued.")
        return 1

    print("\nBuilding a reference parser from your grammar and testing valid programs...\n")
    for snippet in VALID_SNIPPETS:
        try:
            ok = accepts(grammar, snippet)
        except GrammarError as e:
            check(f"accepts valid snippet {snippet!r} (grammar error: {e})", False, failures)
            continue
        check(f"accepts valid snippet: {snippet!r}", ok, failures)

    print("\nTesting invalid programs are correctly rejected...\n")
    for snippet in INVALID_SNIPPETS:
        try:
            ok = accepts(grammar, snippet)
        except GrammarError:
            ok = False  # a grammar error while attempting to parse invalid input counts as "rejected"
        check(f"rejects invalid snippet: {snippet!r}", not ok, failures)

    print()
    if failures:
        print(f"{len(failures)} check(s) failed. No token issued.")
        return 1

    print_success_banner(ASSIGNMENT_ID)
    return 0


if __name__ == "__main__":
    sys.exit(main())
